version: '3' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 angular: # name of the first service
  build: ./angularclientside # specify the directory of the Dockerfile
  ports:
  - "4200:4200" # specify port mapping

 express: # name of the second service
  build: ./express-server # specify the directory of the Dockerfile
  ports:
  - "3000:3000" #specify ports mapping
  depends_on:
  - database
  links:
  - database:mongo # link this service to the database service

 database: # name of the third service
  image: mongo # specify image to build container from
  container_name: mongo
  environment:
  - MONGO_DATA_DIR=/data/db
  - MONGO_LOG_DIR=/dev/null
  volumes:
  - /Users/gcit/mongo:/data/db
  ports:
  - "27017:27017" # specify port forwarding
  expose:
  - "27017"
  hostname: mongo